# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - testdemotest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_6f816a665f994771984db0f3ce2552b3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_916ccc776dfe40a2988ee72fcda2225a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_6f816a665f994771984db0f3ce2552b3 }}/azure-app-service/windows/parkingpage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'testdemotest'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f80cd855a80e4a35b0c0bd8d1545cb82 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_6f816a665f994771984db0f3ce2552b3 }}/azure-app-service/windows/parkingpage:${{ github.sha }}'